<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SmartAuditX-34ad1d67-3a1c-4f07-a4a4-c9f00035acf7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <NoWarn>NU1901</NoWarn> <!-- added this to suppress warnings about missing package versions, as we are using central package management in Directory.Packages.props -->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\**" />
    <Content Remove="ViewModels\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="ClosedXML" Version="0.105.0" />
	  <PackageReference Include="Dapper" Version="2.1.79" />
	  <PackageReference Include="MailKit" Version="4.17.0" />
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
	  <PackageReference Include="NuGet.Packaging" Version="6.13.1" />  <!--Updated this to 6.13.1 becuase 6.13.0 stopping commands-->
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="PSC.CSharp.Library.CountryData" Version="8.0.9" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.ImageSharp.V2" Version="0.16.18" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Shared\Layouts\Partials\" />
    <Folder Include="wwwroot\css\Company\" />
    <Folder Include="wwwroot\css\Auditor\" />
    <Folder Include="wwwroot\css\Manager\" />
    <Folder Include="wwwroot\Companylogo\" />
    <Folder Include="wwwroot\css\Admin\" />
    <Folder Include="wwwroot\js\Admin\" />
    <Folder Include="wwwroot\js\Auditor\" />
    <Folder Include="wwwroot\js\Company\" />
    <Folder Include="wwwroot\js\Manager\" />
    <Folder Include="wwwroot\js\Public\" />
    <Folder Include="wwwroot\EmployeeDocuments\" />
  </ItemGroup>

</Project>
